In [44]:
import transformer_lens
from transformer_lens import utils
import torch
import tqdm
# Load a model (eg GPT-2 Small)
model = transformer_lens.HookedTransformer.from_pretrained("gpt2-small")

# Run the model and get logits and activations
logits, activations = model.run_with_cache("Hello World my dear")

Using pad_token, but it is not set yet.


Loaded pretrained model gpt2-small into HookedTransformer


In [73]:

data = []
max_tokens = 20
for i in torch.range(0.8,1.8,0.05).tolist():
    text, logits, tokens = model.generate("Hello world", max_new_tokens= max_tokens, temperature= i)
    data.append([i,text, logits, tokens])



/var/folders/_j/ctxbrk0926zg7z8n7jc3xpp00000gn/T/ipykernel_11040/2011263488.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  for i in torch.range(0.8,1.8,0.05).tolist():
 10%|█         | 2/20 [00:00<00:01, 13.28it/s]

In [72]:
for i, text, logits, tokens in data:
    try:
        tokens = tokens[:,-max_tokens:]
        tokens = tokens.view(-1, 1)
        value = torch.gather(logits, 1, tokens)
        print(i, text)
    except:
        pass

0.10000000149011612 tensor(81.4295, device='mps:0')
0.20000000298023224 tensor(87.5925, device='mps:0')
0.30000001192092896 tensor(68.5053, device='mps:0')
0.4000000059604645 tensor(79.9255, device='mps:0')
0.5 tensor(69.7738, device='mps:0')
0.6000000238418579 tensor(96.8554, device='mps:0')
0.699999988079071 tensor(68.2101, device='mps:0')
0.800000011920929 tensor(85.5903, device='mps:0')
0.8999999761581421 tensor(85.8839, device='mps:0')
1.0 tensor(61.7886, device='mps:0')
1.100000023841858 tensor(72.3919, device='mps:0')
1.2000000476837158 tensor(66.9799, device='mps:0')
1.2999999523162842 tensor(61.8307, device='mps:0')
1.399999976158142 tensor(60.4256, device='mps:0')
1.5 tensor(60.7821, device='mps:0')
1.600000023841858 tensor(64.4879, device='mps:0')
1.7000000476837158 tensor(59.6797, device='mps:0')
1.7999999523162842 tensor(59.7458, device='mps:0')
1.899999976158142 tensor(59.6206, device='mps:0')
2.0 tensor(50.8769, device='mps:0')
2.0999999046325684 tensor(40.7702, device='

In [71]:
torch.sort(logits, dim = -1, descending= True)[0][:,:5]

tensor([[12.7509, 12.7170, 12.5355, 12.4696, 12.2838],
        [19.8052, 19.7470, 18.6984, 16.0832, 14.6497],
        [14.4750, 14.0934, 13.9926, 13.7379, 13.7191],
        [16.1593, 14.8881, 14.7670, 14.3517, 14.2724],
        [15.2201, 13.2687, 13.0394, 12.8241, 12.4704],
        [11.3613,  9.8134,  9.6517,  9.6166,  9.5685],
        [14.1785, 13.7162, 12.7836, 12.7243, 12.2793],
        [13.8363, 11.0882, 10.8573, 10.6941, 10.4992],
        [14.3548, 12.9766, 12.7943, 12.1698, 11.6789],
        [10.8068, 10.4383,  9.8973,  9.8159,  9.7728],
        [10.8084, 10.3649,  9.6279,  9.4527,  9.2093],
        [ 9.2586,  8.7829,  8.5969,  8.3090,  8.2467],
        [10.6660, 10.1819,  9.9654,  9.8209,  9.7427],
        [ 9.9492,  9.8800,  9.7281,  9.3512,  9.2401],
        [ 8.9965,  8.6430,  8.5785,  8.4631,  8.3952]], device='mps:0')

tensor([[ 5.6484],
        [ 2.6567],
        [-0.1004],
        [ 0.1126],
        [ 7.0817],
        [15.6195],
        [-4.3886],
        [ 2.8798],
        [ 3.2375],
        [ 4.8523],
        [ 6.8143],
        [ 0.5118],
        [-0.7531],
        [ 1.4893],
        [ 6.3591],
        [ 1.5402],
        [ 3.5337],
        [ 1.8687],
        [-0.5449],
        [ 5.7629],
        [ 5.7563],
        [ 2.2309],
        [ 4.0123],
        [ 2.8444],
        [ 7.9367],
        [ 2.8583],
        [-0.7215],
        [ 2.5008],
        [ 0.8886],
        [ 2.2711],
        [ 2.2518],
        [-0.7330],
        [ 0.4811],
        [ 2.3504],
        [ 4.8240],
        [ 6.4346],
        [ 1.2406],
        [ 1.4503],
        [-1.7843],
        [ 3.2869],
        [ 7.9421],
        [ 3.4974],
        [ 1.8514],
        [-1.0382],
        [ 3.8614],
        [ 1.2364],
        [ 0.3059],
        [ 0.1878],
        [ 2.9810],
        [ 4.3940]], device='mps:0')

John went to Navy sailedacity050 Friday morningynamic Draft arrivesHe alongorkacion FeatherfanMiami o Allah Prescott Florida Tony Imagine Cubs SteandactionPlanet Frankenstein AgencySemHolysawemoEstavenoid Bore Luna probesCydderricking breakupAut nudity Faces Vet Boys man


In [51]:
model.tokenizer.decode(utils.sample_logits(b, temperature= 1))

' hear hospital Hall in on There was great the Warn'

In [30]:
utils.sample_logits(b[0], temperature= 1)

tensor(2342, device='mps:0')

In [32]:
(2342)

' watch'

In [57]:
c = b.softmax(dim= -1)
c[0].max()

tensor(0.1838, device='mps:0')

In [59]:
b.shape

torch.Size([10, 50257])

In [80]:
import torch
d = torch.sort(b, dim = -1, descending= True)[0][:,:5]

In [81]:
d

tensor([[13.8638, 12.4966, 12.3457, 12.3137, 12.2655],
        [12.3876, 11.5795, 11.3871, 11.1814, 11.1573],
        [15.4048, 14.4708, 14.1145, 13.9561, 13.8073],
        [14.0280, 13.0940, 12.9769, 12.7756, 12.7384],
        [15.3550, 15.1812, 14.9407, 14.8036, 14.7779],
        [12.8079, 11.8815, 11.5553, 10.3182, 10.2794],
        [18.2969, 17.7875, 15.8871, 15.3014, 15.1261],
        [14.6709, 14.1500, 13.1387, 13.0301, 12.8473],
        [15.0009, 13.6242, 13.1223, 12.8204, 12.6854],
        [12.3626, 12.1825, 12.0275, 11.5658, 11.5531]], device='mps:0')